# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2024 Robin Jarry
---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -qy git jq curl
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # force fetch all history
      - run: git config --global --add safe.directory $PWD
      - run: .github/workflows/check-commits "${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
        if: ${{ github.event.pull_request.base.sha && github.event.pull_request.head.sha }}
